### PR TITLE
Compression improvements

### PR DESCRIPTION
**Pull request by bmwiedemann**
one bugfix
and three commits that help to get closer to identical compressed files after applying deltas

### CODE REVIEW

**Comment by jmacd** [comment]
I'd like to stall this for a moment.

There's a licensing question:
I am currently planning to re-license the Xdelta code base in the public
domain.
There's a minor complication, and I need to speak with my attorney.
I don't want to worry about CLAs and such, and I just need to make sure I'm
not making mistakes.

The change looks good.
Josh

**Comment by bmwiedemann** [comment]
I happen to know a bit about open-source licensing and remember that for example there is no public-domain in Germany, so licensing under the CC0 license ( https://creativecommons.org/publicdomain/zero/1.0/ ) would be the closest you could get. But for some reason few people do that for code and rather chose the MIT, X11 or BSD (2- or 3-clause) license if they wanted to be very permissive or GPLv2 or GPLv3+ if they want other people to contribute back.

**Comment by bmwiedemann** [comment]
any update on this?

**Comment by jmacd** [comment]
Hi, 
Sorry I broke this pull request, but I did make a change in the license and now I'm trying to find the time to properly release and announce it. After some research, I chose to use APLv2.
The branches are 
https://github.com/jmacd/xdelta/tree/release3_1_apl
https://github.com/jmacd/xdelta/tree/release3_0_apl
Josh

**Comment by bmwiedemann** [comment]
I rebased my branch ontop of your release3_0_apl branch. Want to re-open this PR or should I open a new one?

**Comment by bmwiedemann** [comment]
moved to #255

**Pull request closed without merging**
